dTest/urls.py
from django.conf.urls import url
from django.contrib import admin
from app1 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.login),
    url(r'logout', views.logout),
    url(r'^index', views.index),
    url(r'^add/', views.add),
    url(r'^search_cls/', views.search_cls),
    url(r'^add_cls/', views.add_cls),
    url(r'^edit_cls-(?P<cid>\d+)', views.edit_cls),
    url(r'^delete_cls', views.delete_cls),
    url(r'^search_stu', views.search_stu),
    url(r'^add_stu', views.add_stu),
    url(r'^edit_stu-(?P<sid>\d+)', views.edit_stu),
    url(r'^delete_stu', views.delete_stu),
    url(r'^clas_select/(?P<cousid>\d+)', views.clas_select),
    url(r'^search_course', views.search_course),
    url(r'^del_course', views.del_course),
    url(r'^edit_course',views.edit_course),
    url(r'^add_course',views.add_course),
    url(r'^download_cls',views.download_clas)



]

app1/models.py
from django.db import models

# Create your models here.

CLAS_TYPE = [(1,"现场"),(2,"网络"),]
IS_RECOM = [(1, "是"),(2, "否"),]

class Login(models.Model):
    uname = models.CharField(verbose_name="用户名",max_length=32,unique=True)
    passwd = models.CharField(verbose_name="密码",max_length=32)

#课程类型
class Courses(models.Model):
    couName = models.CharField(verbose_name="班级名称",max_length=64,unique=True)

    def __str__(self):
        return self.couName

#学生表
class Stu(models.Model):
    #nid = models.BigAutoField(primary_key=True)
    #Sno = models.IntegerField(verbose_name='学号',unique=True)
    name = models.CharField(verbose_name='姓名', max_length=64)
    phoneNo = models.CharField(verbose_name='手机号',max_length=20,null=False)
    qqNo = models.CharField(verbose_name='qq号',max_length=15,null=False)
    couId = models.ForeignKey(Courses,default=1,db_constraint=False)
    clsId = models.ForeignKey("Clas",db_constraint=False)
    tuition_total = models.FloatField(verbose_name="应交学费")
    tuition_paid = models.FloatField(verbose_name="已交学费")
    isRecommended = models.IntegerField(verbose_name='是否内部推荐',choices=IS_RECOM,)
    recommender = models.ForeignKey('self',blank=True,null=True,db_constraint=False)
    clsType = models.IntegerField(choices=CLAS_TYPE,default=1,verbose_name="班级类型，1现场，2网络")

    def __str__(self):
        return self.name



#班级表
class Clas(models.Model):
    clsName = models.CharField(verbose_name="班级名称",max_length=128,unique=True)
    startTime = models.DateField(verbose_name="开课时间")
    endTime = models.DateField(verbose_name="结束时间")
    course = models.ForeignKey("Courses",default=1,db_constraint=False)

    def __str__(self):
        return self.clsName

templates/add_cls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增班级</title>
    <style>
        .error-message {
            color: red;
        }
    </style>
</head>
<body>
    <form id="add_form" method="post" action="add_cls.html">
        {% csrf_token %}
        <p>{{ cls_obj.clsId }}</p>
        <p>班级名称{{ cls_obj.clsname }}</p>
        <p>科目{{ cls_obj.coursId }}</p>
        <p>开课日期{{ cls_obj.starttime }}</p>
        <p>结课日期{{ cls_obj.endtime }}</p>

{#        <p><input type="hidden" name="op" value="add"></p>#}

{#        <div class="modal-body">#}
{##}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">班级名</div>#}
{#                    <input name="clsname" class="form-control" type="text" placeholder="请输入班级名">#}
{##}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">开课日期</div>#}
{#                    <input name="starttime" class="form-control" type="text" placeholder="请输入开课日期">#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">结课日期</div>#}
{#                    <input name="endtime" class="form-control" type="text" placeholder="请输入结课日期">#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}
        <div class="modal-footer">
            <a href="/search_cls"><button type="button" class="btn btn-default">取消</button></a>
            <button id="add_cls_button" type="button" class="btn btn-primary">确定</button>
        </div>
         <div id="all_err">
        </div>
    </form>

    <script src="../static/js/jquery-1.12.4.js"></script>
    <script src="../static/js/jquery.cookie.js"></script>
    <script>
        $(function() {
           $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                   xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
           });
           $("#add_cls_button").click(function () {
              var err = $('.error-message');
            if(err.length>0){
                err.remove();<!--防止每点击一次，重复出现一次错误提示-->
            }
            $.ajax({
                url: "#",
                type: "POST",
                data: $('#add_form').serialize(),
                success: function (data) {
                    data = JSON.parse(data);
                    if (data.status) {
                        location.href = "/search_cls";
                    } else {
                        $.each(data.error,function (k,v) {<!--返回的错误信息，添加到相应字段后面-->
                            if ('__all__' == k) {
                                var s = document.createElement('span');
                                s.className = 'error-message';
                                s.innerText = v[0].messages;
                                $('#all_err').html(s);
                            }else{
                                var tag = document.createElement('span');
                                tag.className = 'error-message';
                                tag.innerText = v[0].messages;
                                $('input[name="'+k+'"]').after(tag);
                                $('select[name="'+k+'"]').after(tag);
                            }

                        });
{#                        if(data.error.clsname){#}
{#                            $('#error_msg').text(data.error.clsname[0].messages);#}
{#                        }else{#}
{#                            if(data.error.starttime){#}
{#                                $('#error_msg').text(data.error.starttime[0].messages);#}
{#                            }else{#}
{#                            if(data.error.endtime){#}
{#                                $('#error_msg').text(data.error.endtime[0].messages);#}
{#                            }else{#}
{#                                $('#error_msg').text(data.error);#}
{#                            }#}
{#                        }#}
{#                        }#}

                    }
                }
            });
         });
        })

    </script>

</body>
</html>

templates/add_stu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新增学员</title>
    <style>
        .error-message {
            color: red;
        }
    </style>
</head>
<body>

     <div>

     </div>
     <form id="add_form" method="post" action="add_cls.html">
         {% csrf_token %}
        {# <p>学号{{ stu.stuno }}</p>#}
          <p>学生姓名{{ stu.stuname }}</p>
          <p>手机号{{ stu.phone }}</p>
          <p>QQ号{{ stu.qq }}</p>
          <p>科目{{ stu.coursId }}</p>
          <p>班级{{ stu.clsId }}
{#              {% if res.error.clsId %}#}
{#                  console.log({{ res.error.clsId.0 }})#}
{#                  <span class="error-message">{{ stu.errors.clsId.0}}</span>#}
{#              {% endif %}#}
          </p>
          <p>班级类型{{ stu.clstype }}</p>
          <p>应交学费{{ stu.tu_total }}</p>
          <p>已交学费{{ stu.tu_paid }}</p>
          <p>是否推荐{{ stu.is_recom }}</p>
          <p>推荐人{{ stu.recom}}</p>
         <p>
             <button id="add_stu_button" type="button" >确定</button>
             <button id="add_cancel" type="button" >取消</button>
         </p>
{#         <p>#}
{#             <span class="error_msg" id="error_msg">{{ error_msg}}</span>#}
{#         </p>#}
    </form>

     <script src="../static/js/jquery-1.12.4.js"></script>
     <script src="../static/js/jquery.cookie.js"></script>
     <script>
         $(function() {
             $.ajaxSetup({
                 beforeSend: function (xhr, settings) {
                     xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                 }
             });
             $("#add_stu_button").click(function () {
                 var err = $('.error-message');
                 if (err.length > 0) {
                     err.remove();
                 }
                 $.ajax({
                     url: "#",
                     type: "POST",
                     data: $('#add_form').serialize(),
                     success: function (data) {
                         console.log(data);
                         data = JSON.parse(data);
                         if (data.status) {
                             location.href = "/search_stu";
                         } else {
                             $.each(data.error, function (k, v) {
                                 var tag = document.createElement('span');
                                 tag.className = 'error-message';
                                 tag.innerText = v[0].messages;
                                 $('input[name="' + k + '"]').after(tag);
                                 $('select[name="' + k + '"]').after(tag)

                             });
                             console.log(data.error)
                         }
                     }
                 });
             });
             $("#add_cancel").click(function () {
                 window.location.href = '/search_stu'

             });
         });

         <!--班级与所选课程联动显示-->
         function getClasOption(coursId){
             <!--根据课程id 查询该课程关联的班级-->
             $.ajax({
                 url:"/clas_select/"+coursId,
                 type:"GET",
                 dataType:'json',
                 success:function (data) {
                     var cls = $("#id_clsId").get(0);
                     {# console.log("cls select:",cls);#}
                     var cls_length = cls.options.length;
                     if(cls_length>0){
                         for (var i=cls.length-1;i>-1;i--){
                              cls.options[i]=null;<!--清空当前的班级选项-->
                         }
                         cls.options[0]=new Option("-----","");<!--默认项-->
                     }
                     if(data.length>0){
                         for(var j=1;j<=data.length;j++){
                             <!--将新查询的班级选项展示到下拉列表-->
                             cls.options[j]=new Option(data[j-1].cname,data[j-1].cid);
{#                             cls.options[j].text = data[j].cname;#}
{#                             cls.options[j].value = data[j].cid;#}
                         }
                     }
                 }
             })
         }
     </script>

</body>
</html>

templates/cls_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑班级信息</title>
    <style>
        .error-message {
            color: red;
        }
    </style>
</head>
<body>
    <form id="edit_form" method="post" >
         {% csrf_token %}
         <input name="clsId" value={{cls_select.id}}  type="hidden" />
         <p>班级名称<input name="clsname" value={{cls_select.clsName}}  type="text" /></p>
          <p>科目<select name="coursId"  >
              {% for cs in cos_list %}
                  {% if cls_select.course.id == cs.id %}
                     <option value="{{ cs.id }}"  selected="selected">{{ cs.couName }}</option>
                  {% else %}
                      <option value="{{ cs.id }}" >{{ cs.couName }}</option>
                  {% endif %}

              {% endfor %}


          </select>
          </p>
           <p>开课日期<input name="starttime" value={{ cls_select.startTime|date:"Y-m-d"}}  type="text" /></p>
           <p>结课日期<input name="endtime" value={{ cls_select.endTime|date:"Y-m-d"}}  type="text" /></p>
{#        <div class="modal-body">#}
{##}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">班级名</div>#}
{#                    <input name="clsname" value={{ cls_select.clsName}} class="form-control" type="text" >#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">开课日期</div>#}
{#                    <input name="starttime" value={{ cls_select.startTime}} class="form-control" type="text" placeholder="请输入开课日期">#}
{#                </div>#}
{#            </div>#}
{#            <div class="form-group">#}
{#                <div class="input-group">#}
{#                    <div class="input-group-addon">结课日期</div>#}
{#                    <input name="endtime" value={{ cls_select.endTime}} class="form-control" type="text" placeholder="请输入结课日期">#}
{#                </div>#}
{#            </div>#}
{##}
{#        </div>#}
        <div class="modal-footer">
            <a href="/search_cls"><button type="button" class="btn btn-default">取消</button></a>
            <button id="edit_cls_button" type="button" class="btn btn-primary">确定</button>
        </div>
         <div id="all_err"></div>
    </form>

    <script src="../static/js/jquery-1.12.4.js"></script>
    <script src="../static/js/jquery.cookie.js"></script>
    <script>
        $(function() {
           $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                   xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
           });
          $("#edit_cls_button").click(function () {
              var err = $('.error-message');
            if(err.length>0){
                err.remove();
            }
            $.ajax({
                url: "/edit_cls-{{ cls_select.id }}",
                type: "POST",
                data: $('#edit_form').serialize(),
                success: function (data) {
                    data = JSON.parse(data);
                    if (data.status) {
                        location.href = "/search_cls";
                    } else {
                        $.each(data.error,function (k,v) {
                            if ('__all__' == k) {<!--全局错误提示加在按钮下方-->
                                var s = document.createElement('span');
                                s.className = 'error-message';
                                s.innerText = v[0].messages;
                                $('#all_err').html(s);
                            }
                            else{<!--给字段错误提示加在各字段后面-->
                                var tag = document.createElement('span');
                                tag.className = 'error-message';
                                tag.innerText = v[0].messages;
                                $('input[name="'+k+'"]').after(tag);
                                $('select[name="'+k+'"]').after(tag);}


                        });

                    }
                }
            });
        });
        })

    </script>
</body>
</html>

templates/cls_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>班级管理</title>
    <style>
         .hider{
             display: none;
         }
         .shadow{
             position: fixed;
             left: 0;right: 0;
             bottom: 0;top: 0;
             background-color:silver;
             z-index: 999;
             opacity: 0.4
         }
         .del_modal{
             width: 300px;
             height:200px;
             z-index:1000;
             margin-left: 300px;
             position: fixed;
             left: 240px;
             top: 150px;
             text-align: center
         }

     </style>
</head>
<body>


      <h1>班级管理</h1>
      <form id="search_form"  method="post" action="/search_cls">
           {% csrf_token %}
            <span>科目：<select name="coursId" >
              <option value=0 selected="selected">-----</option>
              {% for cs in cos_list %}
                  <option value="{{ cs.id }}" >{{ cs.couName }}</option>
              {% endfor %}
            </select></span>
           <label for="cname">班级名称:</label>
            <input type="search" name = 'cname' placeholder="请输入班级名称" >
            <button type="submit">搜索</button>
            <input type="button" id="download_btn" value="导出数据"/>
      </form>
     <div >
        <a href="/add_cls">
            <button type="button" >新增班级</button>
        </a>
        <!-- <button id="edit_button" type="button" class="btn btn-primary">
            <i class="fa fa-pencil" aria-hidden="true"></i> 编辑
        </button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#delModal">
            <i class="fa fa-trash-o" aria-hidden="true"></i> 删除
        </button>-->
    </div>

     <table>
        <tr>
            <td>班级名称</td>
            <td>科 目</td>
            <td>开课日期</td>
            <td>结课日期</td>
            <td></td>
            <td></td>
        </tr>
        {% for item in cls_list %}
        <tr>
            <td>{{ item.clsName }}</td>
            <td>{{ item.course }}</td>
            <td>{{ item.startTime|date:"Y年m月d日" }}</td>
            <td>{{ item.endTime|date:"Y年m月d日" }}</td>
            <td><a href="/edit_cls-{{ item.id }}">编辑</a></td>
            <td><button type="button" class="del_btn"  data-id={{ item.id }}>删除</button></td>
        </tr>
        {% endfor %}
    </table>
{#     <div>#}
{#         {{ pager_str }}#}
{#     </div>#}

       <div  id="delModal"  class="del_modal shadow hider">

                <form id="del_form"  method="post">
                    <div class="modal-body">

                        是否确认删除该班级？
                        {#  <input name="delid" type="text" style="display: none">#}
                    </div>
                    <div class="input-group">
                        <input name="clsid" id="delcid"  type="text" style="display: none">
                        <!--<div class="input-group-addon">班级名</div>
                        <input name="clsname" id="delcname"  class="form-control" type="text"  readonly = readonly>-->
                    </div>

                    <div >
                        <button type="button" id="del_cls_no" class="btn btn-default" data-dismiss="modal">取消</button>
                        <button  type="button" id="del_cls_yes" class="btn btn-primary">确定</button>
                    </div>
                </form>
            </div>


    <script src="../static/js/jquery-1.12.4.js"></script>
     <script src="../static/js/jquery.cookie.js"></script>
    <script>
        $(function() {
           $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                   xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                }
           });
           $('.del_btn').click(function () {
              var delcid = $(this).attr("data-id");
              $('#delModal').removeClass("hider");
              $('#delcid').attr("value",delcid);
        });
{#             <!--ajax请求只是个“字符型”的请求，即请求的内容是以文本类型存放的。#}
{#             文件的下载是以二进制形式进行的，虽然可以读取到返回的response，#}
{#             但只是读取而已，是无法执行的，说白点就是js无法调用到浏览器的下载处理机制和程序。#}
{#             $('#download_btn').click(function () {#}
{#                  $.ajax({#}
{#                      url: "/download_cls",#}
{#                      type: "POST",#}
{#                      data: $('#search_form').serialize(),#}
{#                      success: function (data) {#}
{#                          if (data) {#}
{#                              location.reload();#}
{#                              alert("success");#}
{#                          } else {#}
{#                              alert(data);#}
{#                          }#}
{#                      }#}
{#                  });#}
{#             });-->#}
            $('#download_btn').click(function (){
                <!--创建隐形form-->
{#                var  form1 = document.getElementById("search_form");#}
{#                form_hide = form1.cloneNode(true);#}
{#                form_hide.id = "download_form";#}
{#                form_hide.method = "post";#}
{#                form_hide.action = "/download_cls";#}
{#                document.body.appendChild(form_hide);#}
{#                form_hide.action = "/download_cls";#}
                var form_hide = document.createElement("form");
                console.log(form_hide);
                form_hide.id = "download_form";
                form_hide.name = "form_download";
                form_hide.method = "post";
                form_hide.action = "/download_cls";
                form_hide.style.display="none";
                document.body.appendChild(form_hide);
                <!--var cour_select = $('select[name="coursId"]');不是节点元素-->
                var cours1 = document.getElementsByName("coursId")[0];
                var index = cours1.selectedIndex;
                var cour_select = cours1.cloneNode(true);
                cour_select.name = "coursId1";
                cour_select.selectedIndex = index;
                console.log(cour_select);
                form_hide.appendChild(cour_select);

                <!--var name_clas = $('input[name="cname"]');-->
                var clas1 = document.getElementsByName("cname")[0];
                var v = clas1.value;
                var name_clas = clas1.cloneNode(true);
                name_clas.name = "cname1";
                name_clas.value=v;
                console.log(name_clas);
                form_hide.appendChild(name_clas);
                <!--var btn_download = $(this);-->
{#                var btn_download = document.getElementById("download_btn");#}
{#                console.log(btn_download);#}
{#                form_hide.appendChild(btn_download);#}

                var csrf = document.getElementsByName("csrfmiddlewaretoken")[0];
                var csrf1 = csrf.cloneNode(true);
                console.log(csrf);
                form_hide.appendChild(csrf1);
                console.log(form_hide);
                form_hide.submit();
                document.body.removeChild(form_hide);

            });



           $('#del_cls_yes').click(function () {
            $.ajax({
                url: "/delete_cls",
                type: "POST",
                data: $('#del_form').serialize(),
                success: function (data) {
                    if (data == "OK") {
                        location.reload();
                    } else {
                        alert(data);
                    }
                }
            });

        });
           $('#del_cls_no').click(function () {
             $('#delModal').addClass("hider");

             });
        });

    </script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome</title>
</head>
<body>
     <h1>Welcome {{ user }}</h1>
     <div><a href="/search_course">课程管理</a></div>
     <div><a href="/search_cls">班级管理</a></div>
     <div><a href="/search_stu">学生管理</a></div>
     <a href="/logout">
         <button type="button">退出</button>
     </a>



     <script src="../static/js/jquery-1.12.4.js"></script>
     <script src="../static/js/jquery.cookie.js"></script>
     <script>

     </script>

</body>
</html>

templates/stu_list.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>学员管理</title>
    <style>
         .hider{
             display: none;
         }
         .shadow{
             position: fixed;
             left: 0;right: 0;
             bottom: 0;top: 0;
             background-color:silver;
             z-index: 999;
             opacity: 1.0
         }
         .del_modal{
             width: 300px;
             height:200px;
             z-index:1000;
             margin-left: 300px;
             position: fixed;
             left: 240px;
             top: 150px;
             text-align: center
         }

     </style>
</head>
<body>
    <h1>学员管理</h1>
      <form method="post" action="/search_stu">
          {% csrf_token %}
          <div>
            <span>科目：<select name="coursId"  onchange="getClasOption(this.options[selectedIndex].value)">
              <option value=0 selected="selected">-----</option>
              {% for cs in cos_list %}
                <option value="{{ cs.id }}" >{{ cs.couName }}</option>
              {% endfor %}
          </select></span>
          <span>班级：<select name="clsId" id="clsId" >
                <option value=0 selected="selected">-----</option>
{#              {% for cls in cls_list %}#}
{#                <option value="{{ cls.id }}" >{{ cls.clsName }}</option>#}
{#              {% endfor %}#}
          </select></span>
            <label for="sname">学生姓名:</label>
            <input id="sname" type="search" name = 'sname' placeholder="请输入学员姓名" >
              <label for="sqq">QQ号:</label>
            <input id="sqq" type="search" name = 'sqq' placeholder="请输入QQ号" >
               <label for="sphone">电话号码:</label>
            <input id="sphone" type="search" name = 'sphone' placeholder="请输入电话号码" >
            <button type="submit">搜索</button>
          </div>
      </form>

      <div>
        <a href="/add_stu">
            <button type="button">新增学员</button>
        </a>
        <!-- <button id="edit_button" type="button" class="btn btn-primary">
            <i class="fa fa-pencil" aria-hidden="true"></i> 编辑
        </button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#delModal">
            <i class="fa fa-trash-o" aria-hidden="true"></i> 删除
        </button>-->
    </div>

     <table>
        <tr>
            <td>学员姓名</td>
            <td>手机号</td>
            <td>QQ号</td>
            <td>课程类型</td>
            <td>班级</td>
            <td>班级类型</td>
            <td>推荐人</td>
            <td>应交学费</td>
            <td>已交学费</td>
            <td></td>
            <td></td>

        </tr>
        {% for item in stu_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.phoneNo }}</td>
            <td>{{ item.qqNo }}</td>
            <td>{{ item.couId }}</td>
            <td>{{ item.clsId }}</td>
            <td>{{ item.get_clsType_display }}</td>
            <td>{{ item.recommender.name }}</td>
            <td>{{ item.tuition_total }}</td>
            <td>{{ item.tuition_paid }}</td>
            <td><a href="/edit_stu-{{ item.id }}">编辑</a></td>
            <td><button type="button" class="del_btn"  data-id={{ item.id }}>删除</button></td>
        </tr>
        {% endfor %}
    </table>
{#    <div>#}
{#        {{ pager_str }}#}
{#    </div>#}
    <div  id="delModal"  class=" del_modal shadow hider">
                <form id="del_form"  method="post">
                    <div class="modal-body">
                        确定删除该学生？
                        {#  <input name="delid" type="text" style="display: none">#}
                    </div>
                    <div class="input-group">
                        <input name="stuid" id="delsid"  type="text" style="display: none">
                        <!--<div class="input-group-addon">班级名</div>
                        <input name="clsname" id="delcname"  class="form-control" type="text"  readonly = readonly>-->
                    </div>
                    <div >
                        <button type="button" id="del_stu_no" >取消</button>
                        <button type="button" id="del_stu_yes" >确定</button>
                    </div>
                </form>
            </div>

    <script src="../static/js/jquery-1.12.4.js"></script>
    <script src="../static/js/jquery.cookie.js"></script>
    <script>
        $(function() {
              $.ajaxSetup({
                  beforeSend: function (xhr, settings) {
                      xhr.setRequestHeader('X-CSRFtoken', $.cookie('csrftoken'));
                  }
              });
              $('.del_btn').click(function (){
                  var delsid = $(this).attr("data-id");
                  $('#delModal').removeClass("hider");
                  $('#delsid').attr("value",delsid);
              });
              $('#del_stu_yes').click(function () {
                   $.ajax({
                        url: "/delete_stu",
                        type: "POST",
                        data: $('#del_form').serialize(),
                        success: function (data) {
                                 if (data == "OK") {
                                        location.reload();
                                 } else {
                                     alert(data);
                                 }
                        }
                   });

              });
              $('#del_stu_no').click(function () {
                  $('#delModal').addClass("hider");

             });
        });
              function getClasOption(coursId){
                  $.ajax({
                      url:"/clas_select/"+coursId,
                      type:"GET",
                      dataType:'json',
                      success:function (data) {
                     var cls = $("#clsId").get(0);
                     {# console.log("cls select:",cls);#}
                     var cls_length = cls.options.length;
                     if(cls_length>0){
                         for (var i=cls.length-1;i>-1;i--){
                              cls.options[i]=null;
                         }
                         cls.options[0]=new Option("-----",0);
                     }
                     if(data.length>0){
                         console.log("------->",data,data.length);
                         for(var j=1;j<=data.length;j++){
                             cls.options[j]=new Option(data[j-1].cname,data[j-1].cid);
{#                             cls.options[j].text = data[j].cname;#}
{#                             cls.options[j].value = data[j].cid;#}
                         }
                     }
                 }
             });
         }

    </script>
</body>
</html>